"""Fails when the self-hosted serif subset no longer covers the page copy.

Editing index.html / portfolio.html / js/main.js without regenerating the subset
leaves some characters to fall back to a system serif, which is visible as a
mid-sentence font change. Run this after any copy change, or add it to CI:

    python tools/check-font-coverage.py
"""

import os
import sys

from fontTools.ttLib import TTFont

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(BASE, "assets", "fonts")
SOURCES = ("index.html", "portfolio.html", "css/style.css", "js/main.js")
FONTS = ("NotoSerifSC-Regular.woff2", "NotoSerifSC-SemiBold.woff2")

# Generated by JS at runtime, so it never appears verbatim in the sources.
RUNTIME_TEXT = "隐藏号码显示完整号码0123456789/ "


def collect():
    characters = set(RUNTIME_TEXT)
    for relative in SOURCES:
        path = os.path.join(BASE, relative)
        if not os.path.exists(path):
            print(f"skip missing {relative}")
            continue
        with open(path, encoding="utf-8") as handle:
            characters.update(handle.read())
    return {char for char in characters if char.isprintable()}


def main():
    characters = collect()
    print(f"页面文案用到的字符：{len(characters)} 个")
    failures = 0
    for name in FONTS:
        path = os.path.join(FONT_DIR, name)
        if not os.path.exists(path):
            print(f"FAIL  {name} 不存在")
            failures += 1
            continue
        font = TTFont(path)
        cmap = font.getBestCmap()
        missing = sorted(char for char in characters if ord(char) not in cmap)
        if missing:
            failures += 1
            preview = " ".join(f"{c}(U+{ord(c):04X})" for c in missing[:30])
            print(f"FAIL  {name} 缺 {len(missing)} 个字符: {preview}")
        else:
            print(f"PASS  {name} 覆盖完整（{len(cmap)} 个字形，{os.path.getsize(path) / 1024:.1f} KB）")
        font.close()

    if failures:
        print("\n修复：python tools/build-assets.py")
    else:
        print("\n字体子集覆盖完整。")
    return 1 if failures else 0


sys.exit(main())
